# Base configs
baseurl: "https://mykl.rocks"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Mykl Rocks"
subtitle: "See the world through my eyes!"
author: "Mykl Rocks"
header:
 title: "Photography"
 subtitle: "by Mykl Rocks"
footer:
 name: "Hey there, my name is Mykl"
 bio: "Street Photographer."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/myklrocks\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/myklrocks"
  twitter: "https://www.twitter.com/myklrocks"
  instagram: "https://www.instagram.com/myklrocks"
  github: "https://www.github.com/myklrocks"
